In [1]:
from models import *
from datasets import *
import torch
import torch.nn as nn
from pruning.unstructured import *

#has to import eval metrics 

c:\Users\prabh\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: '[WinError 127] The specified procedure could not be found'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
c:\Users\prabh\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(


Importing C:\Users\prabh\Smart-pruner-dev\pruning\unstructured\L1norm.py
Importing C:\Users\prabh\Smart-pruner-dev\pruning\unstructured\train.py
Importing C:\Users\prabh\Smart-pruner-dev\pruning\unstructured\train.py


In [2]:
lenet = Lenet()
mnist= MNIST()
train_dataloader, _ = mnist.get_dataloader()

In [3]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(lenet.parameters(), lr=0.001)

In [4]:
print(list(lenet.conv1.named_parameters())) #before training

[('weight', Parameter containing:
tensor([[[[-0.0233,  0.1106,  0.1920, -0.1157, -0.1862],
          [ 0.1626,  0.1027, -0.1846,  0.1929,  0.1350],
          [ 0.0780, -0.1519,  0.0933, -0.1273,  0.0290],
          [ 0.1166, -0.1459, -0.1400, -0.1546,  0.1799],
          [ 0.0292,  0.0921,  0.0094,  0.1739,  0.0467]]],


        [[[ 0.0673, -0.1937,  0.0150, -0.0135,  0.1546],
          [-0.0288,  0.0129, -0.1814, -0.1603, -0.1347],
          [ 0.0555, -0.0850, -0.1228,  0.0139, -0.0909],
          [-0.1346,  0.1434, -0.0749, -0.0999, -0.1721],
          [ 0.0184,  0.0937,  0.1704,  0.0948,  0.1250]]],


        [[[ 0.0443,  0.0657,  0.0769,  0.1199,  0.1052],
          [-0.0823, -0.0582, -0.1509, -0.1621, -0.1319],
          [-0.1784, -0.1420,  0.0290, -0.0590, -0.1046],
          [-0.1422,  0.0091,  0.1955,  0.0999, -0.0006],
          [-0.0921,  0.1302,  0.0819, -0.1083, -0.1808]]],


        [[[ 0.1206,  0.1892, -0.1783,  0.1600, -0.1000],
          [ 0.0696, -0.1271,  0.1595, -0.1

In [5]:
trainer = Trainer(lenet,5,train_dataloader,criterion,optimizer) 
loss =trainer.train()

  0%|          | 0/5 [00:00<?, ?it/s]

Epoch: 1 | train_loss: 4.4069 | 
Epoch: 2 | train_loss: 3.0324 | 
Epoch: 3 | train_loss: 2.5241 | 
Epoch: 4 | train_loss: 2.1993 | 
Epoch: 5 | train_loss: 1.9016 | 


In [6]:
print(list(lenet.conv1.named_parameters())) #after training

[('weight', Parameter containing:
tensor([[[[ 1.0377e-02,  1.9199e-01,  2.6342e-01, -1.0098e-01, -2.5374e-01],
          [ 2.0907e-01,  1.6116e-01, -1.1583e-01,  2.5863e-01,  8.4947e-02],
          [ 1.2378e-01, -1.5181e-01,  7.2921e-02, -9.1868e-02,  2.5469e-02],
          [ 1.3470e-01, -1.5497e-01, -1.7225e-01, -1.4863e-01,  2.1529e-01],
          [ 1.6509e-02,  1.1905e-01,  4.4589e-02,  1.9053e-01,  5.5813e-02]]],


        [[[ 1.2181e-01, -2.0451e-01, -9.9567e-03, -5.7863e-02,  8.4429e-02],
          [-1.4915e-02, -4.3612e-02, -2.2327e-01, -2.2937e-01, -1.8159e-01],
          [ 8.4670e-02, -1.2583e-01, -1.5268e-01, -1.5662e-02, -7.9464e-02],
          [-6.5079e-02,  1.4520e-01, -7.2233e-02, -8.6229e-02, -6.0131e-02],
          [ 1.3604e-01,  1.8377e-01,  2.7445e-01,  1.9818e-01,  2.3076e-01]]],


        [[[ 1.0433e-01,  9.2068e-02,  1.1018e-01,  1.8690e-01,  1.8521e-01],
          [-1.0056e-01, -9.4418e-02, -1.7914e-01, -1.5061e-01, -1.1722e-01],
          [-1.9594e-01, -1.8633e-0

In [7]:
trainer = UnstructuredL1normPrune(lenet,5,train_dataloader,criterion,optimizer,0.5)
pruned_model = trainer.prune_model()

In [8]:
print(list(pruned_model.conv1.named_parameters()))

[('bias', Parameter containing:
tensor([-0.1785,  0.0084, -0.2480, -0.0593,  0.0988, -0.2323],
       requires_grad=True)), ('weight', Parameter containing:
tensor([[[[ 0.0000,  0.1920,  0.2634, -0.0000, -0.2537],
          [ 0.2091,  0.1612, -0.0000,  0.2586,  0.0000],
          [ 0.1238, -0.1518,  0.0000, -0.0000,  0.0000],
          [ 0.1347, -0.1550, -0.1722, -0.1486,  0.2153],
          [ 0.0000,  0.1190,  0.0000,  0.1905,  0.0000]]],


        [[[ 0.1218, -0.2045, -0.0000, -0.0000,  0.0000],
          [-0.0000, -0.0000, -0.2233, -0.2294, -0.1816],
          [ 0.0000, -0.1258, -0.1527, -0.0000, -0.0000],
          [-0.0000,  0.1452, -0.0000, -0.0000, -0.0000],
          [ 0.1360,  0.1838,  0.2745,  0.1982,  0.2308]]],


        [[[ 0.0000,  0.0000,  0.0000,  0.1869,  0.1852],
          [-0.0000, -0.0000, -0.1791, -0.1506, -0.0000],
          [-0.1959, -0.1863, -0.0000, -0.0000, -0.1227],
          [-0.1776, -0.0000,  0.0000,  0.0000, -0.0000],
          [-0.1241,  0.0000,  0.0000,